library/urls.py
from django.urls import path

from library import views
from .views import (AuthorList, AuthorDetail, SectionList, SectionDetail, BookList, BookDetail,
                    GenreList, GenreDetail, PublisherList, PublisherDetail, AuthorCreate, SectionCreate,
                    BookCreate, GenreCreate, PublisherCreate, AuthorUpdate, AuthorDelete, SectionUpdate, SectionDelete,
                    BookUpdate, BookDelete, GenreUpdate, GenreDelete, PublisherUpdate, PublisherDelete, MemberList,
                    MemberDetail, MemberCreate, MemberUpdate, MemberDelete)

urlpatterns = [
    path('author/',
         AuthorList.as_view(),
         name='library_author_list_urlpattern'),

    path('author/<int:pk>/',
         AuthorDetail.as_view(),
         name='library_author_detail_urlpattern'),

    path('author/create/',
         AuthorCreate.as_view(),
         name='library_author_create_urlpattern'),

    path('author/<int:pk>/update/',
         AuthorUpdate.as_view(),
         name='library_author_update_urlpattern'),

    path('author/<int:pk>/delete/',
         AuthorDelete.as_view(),
         name='library_author_delete_urlpattern'),

    path('section/',
         SectionList.as_view(),
         name='library_section_list_urlpattern'),

    path('section/<int:pk>/',
         SectionDetail.as_view(),
         name='library_section_detail_urlpattern'),

    path('section/create/',
         SectionCreate.as_view(),
         name='library_section_create_urlpattern'),

    path('section/<int:pk>/update/',
         SectionUpdate.as_view(),
         name='library_section_update_urlpattern'),

    path('section/<int:pk>/delete/',
         SectionDelete.as_view(),
         name='library_section_delete_urlpattern'),

    path('book/',
         BookList.as_view(),
         name='library_book_list_urlpattern'),

    path('book/<int:pk>/',
         BookDetail.as_view(),
         name='library_book_detail_urlpattern'),

    path('book/create/',
         BookCreate.as_view(),
         name='library_book_create_urlpattern'),

    path('book/<int:pk>/update/',
         BookUpdate.as_view(),
         name='library_book_update_urlpattern'),

    path('book/<int:pk>/delete/',
         BookDelete.as_view(),
         name='library_book_delete_urlpattern'),

    path('member/',
         MemberList.as_view(),
         name='library_member_list_urlpattern'),

    path('member/<int:pk>/',
         MemberDetail.as_view(),
         name='library_member_detail_urlpattern'),

    path('member/create/',
         MemberCreate.as_view(),
         name='library_member_create_urlpattern'),

    path('member/<int:pk>/update/',
         MemberUpdate.as_view(),
         name='library_member_update_urlpattern'),

    path('member/<int:pk>/delete/',
         MemberDelete.as_view(),
         name='library_member_delete_urlpattern'),

    path('genre/',
         GenreList.as_view(),
         name='library_genre_list_urlpattern'),

    path('genre/<int:pk>/',
         GenreDetail.as_view(),
         name='library_genre_detail_urlpattern'),

    path('genre/create/',
         GenreCreate.as_view(),
         name='library_genre_create_urlpattern'),

    path('genre/<int:pk>/update/',
         GenreUpdate.as_view(),
         name='library_genre_update_urlpattern'),

    path('genre/<int:pk>/delete/',
         GenreDelete.as_view(),
         name='library_genre_delete_urlpattern'),

    path('publisher/',
         PublisherList.as_view(),
         name='library_publisher_list_urlpattern'),

    path('publisher/<int:pk>/',
         PublisherDetail.as_view(),
         name='library_publisher_detail_urlpattern'),

    path('publisher/create/',
         PublisherCreate.as_view(),
         name='library_publisher_create_urlpattern'),

    path('publisher/<int:pk>/update/',
         PublisherUpdate.as_view(),
         name='library_publisher_update_urlpattern'),

    path('publisher/<int:pk>/delete/',
         PublisherDelete.as_view(),
         name='library_publisher_delete_urlpattern'),
]

library/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.


class Author(models.Model):
    author_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=False, blank=False)
    date_of_death = models.DateField(null=True,blank=True)

    def __str__(self):

     result = ''
     if self.date_of_death is None:
        result = '%s , %s (%s - )' % (self.last_name, self.first_name, self.date_of_birth)
     else:
        result = '%s , %s  (%s - %s) ' % (self.last_name, self.first_name, self.date_of_birth, self.date_of_death)
     return result

    def get_absolute_url(self):
        return reverse('library_author_detail_urlpattern',
                       kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('library_author_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('library_author_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['last_name','first_name']
        unique_together = (('last_name', 'first_name'),)


class Publisher(models.Model):
    publisher_id = models.AutoField(primary_key=True)
    publisher_name = models.CharField(max_length = 200, unique=True)

    def __str__(self):
        return '%s' % self.publisher_name

    def get_absolute_url(self):
        return reverse('library_publisher_detail_urlpattern',
                       kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('library_publisher_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('library_publisher_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['publisher_name']


class Book(models.Model):
    book_id = models.AutoField(primary_key=True)
    book_name = models.CharField(max_length=200)
    language = models.CharField(max_length=50)
    author = models.ForeignKey(Author, related_name='books', on_delete=models.PROTECT)
    publisher = models.ForeignKey(Publisher, related_name='books', on_delete=models.PROTECT)

    def __str__(self):
        return '%s - ( %s , %s)' %(self.book_name, self.author.last_name, self.author.first_name)

    def get_absolute_url(self):
        return reverse('library_book_detail_urlpattern',
                       kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('library_book_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('library_book_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['book_name','author__last_name']
        unique_together = (('book_name','author'),)


class Genre(models.Model):
    genre_id = models.AutoField(primary_key=True)
    genre_name = models.CharField(max_length=50, unique = True)

    def __str__(self):
        return '%s' % self.genre_name

    def get_absolute_url(self):
        return reverse('library_genre_detail_urlpattern',
                       kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('library_genre_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('library_genre_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['genre_name']


class Section(models.Model):
    section_id = models.AutoField(primary_key=True)
    genre = models.ForeignKey(Genre, related_name='sections', on_delete=models.PROTECT)
    book = models.ForeignKey(Book, related_name='sections', on_delete=models.PROTECT)

    def __str__(self):
        return '%s - %s' % (self.book.book_name, self.genre.genre_name)

    def get_absolute_url(self):
        return reverse('library_section_detail_urlpattern',
                       kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('library_section_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('library_section_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['genre__genre_name', 'book__book_name']
        unique_together = (('genre', 'book'),)


class Member(models.Model):
    member_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)

    def __str__(self):
        return '%s, %s' % (self.last_name, self.first_name)

    def get_absolute_url(self):
        return reverse('library_member_detail_urlpattern',
                       kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('library_member_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('library_member_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['last_name', 'first_name']

library/forms.py
from django import forms
from library.models import Book, Section, Author, Genre, Publisher, Member
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime


class DateInput(forms.DateInput):
    input_type = 'date'


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = '__all__'
        widgets = {
            'date_of_birth' : DateInput(),
            'date_of_death' : DateInput()
        }

    def clean_first_name(self):
        return self.cleaned_data['first_name'].strip()

    def clean_last_name(self):
        return self.cleaned_data['last_name'].strip()

    def clean_date_of_birth(self):
        return self.cleaned_data['date_of_birth']

    def clean_date_of_death(self):
        data = self.cleaned_data['date_of_death']

        if data is None:
            return data
        if data < self.clean_date_of_birth():
            raise ValidationError(_('Invalid date - Date of Death should be after Date of Birth'))
        else:
            return data


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'

    def clean_book_name(self):
        return self.cleaned_data['book_name'].strip()

    def clean_language(self):
        return self.cleaned_data['language'].strip()


class SectionForm(forms.ModelForm):
    class Meta:
        model = Section
        fields = '__all__'


class MemberForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = '__all__'

    def clean_first_name(self):
        return self.cleaned_data['first_name'].strip()

    def clean_last_name(self):
            return self.cleaned_data['last_name'].strip()


class GenreForm(forms.ModelForm):
    class Meta:
        model = Genre
        fields = '__all__'

    def clean_genre_name(self):
        return self.cleaned_data['genre_name'].strip()


class PublisherForm(forms.ModelForm):
    class Meta:
        model = Publisher
        fields = '__all__'

    def clean_publisher_name(self):
        return self.cleaned_data['publisher_name'].strip()

library/templates/library/author_detail.html
{% extends 'library/base.html' %}

{% block title %}
    Author - {{ author }}
{% endblock %}

{% block content %}
      <article>
          <div class="row">
             <div class="offset-by-two eight columns">
                 <h4 class="margin-tb-10px">{{ author }}</h4>
                    <ul class="inline">
                        {% if perms.library.change_author %}
                        <li>
                          <a
                              href="{{ author.get_update_url }}"
                              class="button">
                            Edit Author</a></li>
                        {% endif %}

                        {% if perms.library.delete_author %}
                        <li>
                          <a
                              href="{{ author.get_delete_url }}"
                              class="button">
                            Delete Author</a></li>
                        {% endif %}
                    </ul>

                <section>
                    <table>
                        <tr>
                            <th>First Name:</th>
                            <td>{{ author.first_name }}</td>
                        </tr>

                        <tr>
                            <th>Last Name:</th>
                            <td>{{ author.last_name }}</td>
                        </tr>

                        <tr>
                            <th>Date of Birth:</th>
                            <td>{{ author.date_of_birth }}</td>
                        </tr>

                        <tr>
                        {% if author.date_of_death is None %}
                                <th>Date of Death:</th>
                                <td>-</td>
                        {% else %}
                                <th>Date of Death:</th>
                                <td>{{ author.date_of_death }}</td>
                        {% endif %}

                        </tr>
                    </table>

                </section>

                <section>
                    <h4>Books</h4>
                    <ul>
                        {% for book in book_list %}
                            <li>
                                <a href="{{ book.get_absolute_url }}">{{ book }}</a>
                            </li>
                        {% empty %}
                            <li><em>There are currently no books for this Author.</em></li>
                        {% endfor %}
                    </ul>
                </section>

             </div>
          </div>
      </article>
{% endblock %}

library/templates/library/author_form.html
{% extends 'library/base.html' %}

{% block title %}
    Create Author
{% endblock %}

{% block content %}
    <form
        action="{% url 'library_author_create_urlpattern' %}"
        method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Author</button>
    </form>
{% endblock %}

library/templates/library/author_refuse_delete.html
{% extends 'library/base.html' %}

{% block title %}
    Error Deleting Author
{% endblock %}

{% block content %}
    <div>
        <h2>Error Deleting Author</h2>
        <p>
            You may not delete the author {{ author }}. This
            author has written the following books
        </p>

        <ul>
            {% for book in books %}
             <li><a href="{{ book.get_absolute_url }}">{{ book }}</a></li>
            {% endfor %}
        </ul>
        <p>
            Return to <a href="{% url 'library_author_list_urlpattern' %}" class="button">Author List</a>
        </p>
    </div>
{% endblock %}

library/templates/library/base.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Title is Provided By Inheriting Templates
        {% endblock %}
    </title>

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--[if IE]><script
      src="http://html5shiv.googlecode.com/svn/trunk/html5.js">
    </script><![endif]-->
    <link rel="stylesheet" type="text/css"
          href="{% static 'library/normalize.css' %}">
    <link rel="stylesheet" type="text/css"
          href="{% static 'library/skeleton.css' %}">
    <link rel="stylesheet" type="text/css"
          href="{% static 'library/style.css' %}"><![endif]-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>

<body>

    <header class = 'row '>
        <div class="margin-l-r-5px">
            <div class="logo logo-dim"></div>
            <div class="header-text">Library Management System</div>
    <div class="float-right login-out">

        {% if user.is_authenticated %}
            <div class="">

                <a href="{% url 'logout_urlpattern' %}" title="Click to Logout" style="text-decoration: none">
                    <i class="material-icons logout-icon">person</i>
                    <div class="color-white">{{ user.get_username|upper }}</div></a></div>
        {% else %}
            <div class="button"><a style="color:#ffffff" href="{% url 'login_urlpattern' %}">
                Log In</a></div>
        {% endif %}
    </div>

        </div>
    <div class="nav">
            <a href="{% url 'index_urlpattern' %}">
                Index</a></li>


            {% if perms.library.view_book %}
                <a href="{% url 'library_book_list_urlpattern' %}">
                    Books</a></li>
            {% endif %}

            {% if perms.library.view_author %}
                <a href="{% url 'library_author_list_urlpattern' %}">
                    Authors</a></li>
            {% endif %}

            {% if perms.library.view_member %}
                <a href="{% url 'library_member_list_urlpattern' %}">
                    Members</a></li>
            {% endif %}

            {% if perms.library.view_section %}
                <a href="{% url 'library_section_list_urlpattern' %}">
                    Sections</a></li>
            {% endif %}

            {% if perms.library.view_genre %}
                <a href="{% url 'library_genre_list_urlpattern' %}">
                    Genres</a></li>
            {% endif %}

            {% if perms.library.view_publisher %}
                <a href="{% url 'library_publisher_list_urlpattern' %}">
                    Publishers</a></li>
            {% endif %}

        </div>
    </header>
<div class="container-img">
    <div class="container"><!-- start of container -->
    <main>
        {% block content %}
            <div class="row background-img">
                <section class="eight columns padding-10px">
                    {% block org_content %}
                        This is default content!
                    {% endblock %}
                </section>
                <section class="desktop four columns">
                    {% block create_button %}{% endblock %}
                </section>
                {% if is_paginated %}
        <div class="row">
            <div class="eight columns">
                <ul class="pagination list">
                    {% if first_page_url %}
                        <li>
                            <a href="{{ first_page_url }}">
                                First</a>
                        </li>
                    {% endif %}
                    {% if previous_page_url %}
                        <li>
                            <a href="{{ previous_page_url }}">
                                Previous</a>
                        </li>
                    {% endif %}
                    <li>
                        Page {{ page_obj.number }}
                        of {{ paginator.num_pages }}
                    </li>
                    {% if next_page_url %}
                        <li>
                            <a href="{{ next_page_url }}">
                                Next</a>
                        </li>
                    {% endif %}
                    {% if last_page_url %}
                        <li>
                            <a href="{{ last_page_url }}">
                                Last</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    {% endif %}
            </div>
            <div class="row">
                <div class="twelve columns">
                    {% block content_footer %}{% endblock %}
                </div>
            </div>
        {% endblock %}
    </main>

<!-- end of container -->
</div>
</div>


<footer>
    <p>
        <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">
            <img alt="Creative Commons License" style="border-width:0"
                 src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png"/>
        </a><br/><span property="dct:title">Online Library Management System code</span>
        is licensed under a
        <a class="color-white" rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike
            4.0 International License</a>.
    </p>
    <p>Portions of the Online Library ManagementSystem code are based upon code from
        <a  class="color-white" href="https://django-unleashed.com">Django Unleashed</a>,
        <a  class="color-white" href="http://getskeleton.com/">Skeleton</a>, and
        <a  class="color-white" href="https://necolas.github.io/normalize.css/">Normalize.css</a> and
        are subject to the intellectual property rights restrictions of those works.
    </p>
</footer>

</body>
</html>

library/templates/library/genre_confirm_delete.html
{% extends 'library/base.html' %}

{% block title %}
    Delete Genre
{% endblock %}

{% block content %}
    <form
        action="{{ genre.get_delete_url }}"
        method='post'>
        {% csrf_token %}
        <p>
            Are you sure that you want to delete the Genre {{ genre }} ?
        </p>
        <a href="{{ author.get_absolute_url }}" class="button">Cancel</a>
        <button type="submit">Delete Genre</button>
    </form>
{% endblock %}

library/templates/library/genre_form.html
{% extends 'library/base.html' %}

{% block title %}
    Create Genre
{% endblock %}

{% block content %}
    <form
        action="{% url 'library_genre_create_urlpattern' %}"
        method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Genre</button>
    </form>
{% endblock %}

library/templates/library/member_confirm_delete.html
{% extends 'library/base.html' %}

{% block title %}
    Delete Member
{% endblock %}

{% block content %}
    <form
        action="{{ member.get_delete_url }}"
        method='post'>
        {% csrf_token %}
        <p>
            Are you sure that you want to delete the member {{ member }} ?
        </p>
        <a href="{{ member.get_absolute_url }}" class="button">Cancel</a>
        <button type="submit">Delete Member</button>
    </form>
{% endblock %}

library/templates/library/member_detail.html
{% extends 'library/base.html' %}

{% block title %}
    Member - {{ member }}
{% endblock %}

{% block content %}
    <article>
        <div class="row">
            <div class="offset-by-two eight columns">
                 <h4 class="margin-tb-10px">{{ member }}</h4>
                    <ul class="inline">
                        {% if perms.library.change_member %}
                        <li>
                          <a
                              href="{{ member.get_update_url }}"
                              class="button">
                            Edit Member</a></li>
                        {% endif %}

                        {% if perms.library.delete_member %}
                        <li>
                          <a
                              href="{{ member.get_delete_url }}"
                              class="button">
                            Delete Member</a></li>
                        {% endif %}
                    </ul>
                    <section>
                        <table>
                            <tr>
                                <th>First Name:</th>
                                <td>{{ member.first_name }}</td>
                            </tr>

                            <tr>
                                <th>Last Name:</th>
                                <td>{{ member.last_name }}</td>
                            </tr>

                        </table>

                    </section>
            </div>
        </div>
    </article>
    
{% endblock %}

library/templates/library/member_form.html
{% extends 'library/base.html' %}

{% block title %}
    Create Member
{% endblock %}

{% block content %}
    <form
        action="{% url 'library_member_create_urlpattern' %}"
        method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Member</button>
    </form>
{% endblock %}

library/templates/library/member_refuse_delete.html
{% extends 'library/base.html' %}

{% block title %}
    Error Deleting Member
{% endblock %}

{% block content %}
    <div>
        <h2>Error Deleting Member</h2>
        <p>
            You may not delete the member {{ member }}.
        </p>
        <p>
            Return to <a href="{% url 'library_member_list_urlpattern' %}" class="button">Member List</a>
        </p>
    </div>
{% endblock %}

library/templates/library/publisher_confirm_delete.html
{% extends 'library/base.html' %}

{% block title %}
    Delete Publisher
{% endblock %}

{% block content %}
    <form
        action="{{ publisher.get_delete_url }}"
        method='post'>
        {% csrf_token %}
        <p>
            Are you sure that you want to delete the author {{ publisher }} ?
        </p>
        <a href="{{ publisher.get_absolute_url }}" class="button">Cancel</a>
        <button type="submit">Delete Publisher</button>
    </form>
{% endblock %}

library/templates/library/publisher_form.html
{% extends 'library/base.html' %}

{% block title %}
    Create Publisher
{% endblock %}

{% block content %}
    <form
        action="{% url 'library_publisher_create_urlpattern' %}"
        method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Publisher</button>
    </form>
{% endblock %}

library/templates/library/section_form.html
{% extends 'library/base.html' %}

{% block title %}
    Create Section
{% endblock %}

{% block content %}
    <form
        action="{% url 'library_section_create_urlpattern' %}"
        method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Section</button>
    </form>
{% endblock %}

library/templates/library/section_list.html
{% extends 'library/base.html' %}

{% block title %}
    Section List
{% endblock %}

{% block create_button %}
    {% if perms.library.add_section %}
    <a
        href="{% url 'library_section_create_urlpattern'  %}"
        class="button button-primary add-button">
      <i class="material-icons" style="font-size: 12px">add_circle</i> <span style="font-size: 12px">
        Create New Section </span>
    </a>
    {% endif %}
{% endblock %}

{% block org_content %}
  <h3>Section List</h3>
    {% if perms.library.add_section %}
    <div class="mobile">
      <a
          href="{% url 'library_section_create_urlpattern' %}"
          class="button button-primary">
        Create New Section</a>
    </div>
    {% endif %}

    <ul class="list">

      {% for section in section_list %}
        <li>
            <a href="{{ section.get_absolute_url }}"> {{ section }}</a>
        </li>

      {% empty %}

          <p>There are no sections in the library.</p>

      {% endfor %}

    </ul>
{% endblock %}